language: android
jdk: oraclejdk8
sudo: required

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# disable the default submodule logic so the gutenberg-mobile submodule is not pulled. No need to pull it.
git:
  submodules: false

notifications:
  # Slack notification on failure (secured token).
  slack:
    rooms:
      secure: sOTcwi1DT0lJykB/smJQwJ5lQblg9jc5PtLsTu4euI/P4nCv1CPu5DVZ1aDwXL6TPDUO5uEwbzbjVFZzrl2nFdAV9XvGT3wL3Zrm2Y5HBtwi8JWdbc4dYR/xobJlIg7HRczXwoFt6yls4BUayNJJbZFV9q0ftmUSe77Pag/ZWQw=
    on_failure: always
    on_success: change

android:
  components:
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    - platform-tools
    - tools
    - build-tools-27.0.3
    - android-27

env:
  global:
    - MALLOC_ARENA_MAX=2
    - GRADLE_OPTS="-XX:MaxPermSize=4g -Xmx4g"

matrix:
  include:
    - name: "Lint & Danger"
      env: GRADLE_TASKS="checkstyle ktlint lintVanillaRelease" EXEC_DANGER=true
      language: ruby
      rvm: 2.3.4
      cache:
        directories:
          - vendor/bundle/
    - name: "Build & Test"
      env: GRADLE_TASKS="assembleVanillaRelease testVanillaRelease"
    - name: "Check Login Strings"
      env: GRADLE_TASKS=""
      script:
        - ./tools/validate-login-strings.sh

install:
  # Setup gradle.properties
  - cp gradle.properties-example gradle.properties
  - cp libs/login/gradle.properties-example libs/login/gradle.properties
  - if [ -n "$EXEC_DANGER" ]; then bundle install; fi

script:
  - ./gradlew --stacktrace -PdisablePreDex $GRADLE_TASKS || (grep -A20 -B2 'severity="Error"' -r --include="*.xml" WordPress libs; exit 1)
  -  if [ -n "$EXEC_DANGER" ]; then if [ -n "$DANGER_GITHUB_API_TOKEN" ]; then bundle exec danger --fail-on-errors=true; else echo "Not running danger because $DANGER_GITHUB_API_TOKEN is not found"; fi; fi