version: 2.1

orbs:
  android: wordpress-mobile/android@0.0.22
  bundle-install: toshimaru/bundle-install@0.1.1

commands:
  copy-gradle-properties:
    steps:
      - run:
          name: Setup gradle.properties
          command: cp gradle.properties-example gradle.properties

jobs:
  Test:
    executor: 
      name: android/default
      api-version: "28"
    steps:
      - checkout
      - copy-gradle-properties
      - android/restore-gradle-cache
      - run:
          name: Test
          command: ./gradlew --stacktrace testVanillaRelease
      - android/save-gradle-cache
      - android/save-test-results
  Lint:
    executor: 
      name: android/default
      api-version: "28"
    steps:
      - checkout
      - copy-gradle-properties
      - android/restore-gradle-cache
      - run:
          name: Checkstyle
          command: ./gradlew --stacktrace checkstyle
      - run:
          name: ktlint
          command: ./gradlew --stacktrace ktlint
      - run:
          name: Lint
          command: ./gradlew --stacktrace lintVanillaRelease || (grep -A20 -B2 'severity="Error"' -r --include="*.xml" WordPress libs; exit 1)
      - android/save-gradle-cache
      - android/save-lint-results
  Strings Check:
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout
      - bundle-install/bundle-install
      - run:
          name: Validate login strings
          command: bundle exec fastlane validate_login_strings pr_url:$CIRCLE_PULL_REQUEST

workflows:
  wordpress_android:
    jobs:
      - Strings Check
      - Test
      - Lint
